base.archivesName = "cinderscapes-worldgen"

loom {
    accessWidenerPath = file("src/main/resources/cinderscapes-worldgen.accesswidener")
}

dependencies {
    implementation project(path: ':cinderscapes-common')

    // Biolith for the worldgen API module
    implementation "com.terraformersmc:biolith-fabric:${biolith_version}"
}
